import { useEffect, useState } from "react";
import {
  ShieldAlert,
  Bell,
  Clock,
  Route,
  ArrowRight,
} from "lucide-react";

import { getActionRecommendations } from "../services/api";

type ActionItem = {
  priority: string;
  location: string;
  action: string;
  risk?: string;
  time?: string;
  reason?: string;
  icon: typeof ShieldAlert;
};

const fallbackActions: ActionItem[] = [
  {
    priority: "Immediate",
    location: "Saidapet",
    risk: "91/100",
    time: "45–60 min",
    reason: "Backend simulated critical flood condition",
    action: "Deploy drainage response team",
    icon: ShieldAlert,
  },
  {
    priority: "High",
    location: "Velachery",
    risk: "Demo",
    time: "Demo",
    reason: "Backend simulated high-priority condition",
    action: "Inspect vulnerable drainage points",
    icon: Bell,
  },
  {
    priority: "High",
    location: "T. Nagar",
    risk: "Demo",
    time: "Demo",
    reason: "Backend simulated high-priority condition",
    action: "Prepare public warning",
    icon: Route,
  },
  {
    priority: "Monitor",
    location: "Adyar",
    risk: "Demo",
    time: "Demo",
    reason: "Backend simulated monitoring condition",
    action: "Continue water-level monitoring",
    icon: Clock,
  },
];

function getIcon(priority: string) {
  if (priority === "Immediate") return ShieldAlert;
  if (priority === "High") return Bell;
  return Clock;
}

export default function AIActionEngine() {
  const [actions, setActions] =
    useState<ActionItem[]>(fallbackActions);

  const [loading, setLoading] = useState(true);
  const [backendError, setBackendError] = useState(false);

  useEffect(() => {
    async function loadActions() {
      try {
        setLoading(true);
        setBackendError(false);

        const response = await getActionRecommendations();

        if (Array.isArray(response?.recommendations)) {
          const mappedActions: ActionItem[] =
            response.recommendations.map((item: any) => ({
              priority: item.priority,
              location: item.area,
              action: item.action,
              risk: "Backend",
              time: "Demo",
              reason:
                "Recommendation generated from simulated backend flood-risk conditions",
              icon: getIcon(item.priority),
            }));

          setActions(mappedActions);
        }
      } catch (error) {
        console.error(
          "AI Action Engine backend error:",
          error
        );

        setBackendError(true);
        setActions(fallbackActions);
      } finally {
        setLoading(false);
      }
    }

    loadActions();
  }, []);

  const criticalCount = actions.filter(
    (item) => item.priority === "Immediate"
  ).length;

  const highCount = actions.filter(
    (item) => item.priority === "High"
  ).length;

  const highestPriority =
    actions.find((item) => item.priority === "Immediate") ??
    actions.find((item) => item.priority === "High") ??
    actions[0];

  return (
    <div className="space-y-6">

      {/* Backend Status */}
      {loading && (
        <div className="rounded-xl border border-blue-200 bg-blue-50 p-4">
          <p className="text-sm font-semibold text-blue-900">
            Loading action recommendations...
          </p>
        </div>
      )}

      {backendError && !loading && (
        <div className="rounded-xl border border-amber-200 bg-amber-50 p-4">
          <p className="text-sm font-semibold text-amber-900">
            Backend unavailable — showing DEMO / SIMULATED DATA.
          </p>
        </div>
      )}

      {/* Header */}
      <div>
        <h1 className="text-3xl font-bold text-slate-900">
          AI Action Engine
        </h1>

        <p className="mt-1 text-sm text-slate-500">
          Actions generated from simulated backend flood-risk
          conditions.
        </p>
      </div>

      {/* Summary Cards */}
      <div className="grid gap-4 md:grid-cols-3">

        <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
          <p className="text-sm text-slate-500">
            Total Recommendations
          </p>

          <p className="mt-2 text-3xl font-bold text-slate-900">
            {actions.length}
          </p>

          <p className="mt-2 text-xs text-slate-500">
            Generated by backend
          </p>
        </div>

        <div className="rounded-xl border border-red-200 bg-red-50 p-5 shadow-sm">
          <p className="text-sm text-red-600">
            Immediate Actions
          </p>

          <p className="mt-2 text-3xl font-bold text-red-700">
            {criticalCount}
          </p>

          <p className="mt-2 text-xs text-red-600">
            Requires immediate authority attention
          </p>
        </div>

        <div className="rounded-xl border border-orange-200 bg-orange-50 p-5 shadow-sm">
          <p className="text-sm text-orange-600">
            High Priority
          </p>

          <p className="mt-2 text-3xl font-bold text-orange-700">
            {highCount}
          </p>

          <p className="mt-2 text-xs text-orange-600">
            Requires monitoring and response
          </p>
        </div>

      </div>

      {/* Highest Priority */}
      {highestPriority && (
        <div className="rounded-xl border border-red-200 bg-white p-6 shadow-sm">

          <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">

            <div>
              <span className="w-fit rounded-full bg-red-100 px-3 py-1 text-xs font-bold text-red-700">
                {highestPriority.priority.toUpperCase()}
              </span>

              <p className="mt-2 text-xl font-bold text-slate-900">
                {highestPriority.location}
              </p>
            </div>

            <div>
              <p className="text-xs uppercase text-slate-500">
                Risk
              </p>

              <p className="mt-1 text-xl font-bold text-red-600">
                {highestPriority.risk ?? "Backend"}
              </p>
            </div>

            <div>
              <p className="text-xs uppercase text-slate-500">
                Expected Time
              </p>

              <p className="mt-1 text-xl font-bold text-orange-600">
                {highestPriority.time ?? "Demo"}
              </p>
            </div>

          </div>

          <p className="mt-4 text-sm text-slate-600">
            {highestPriority.reason ??
              "Backend simulated flood-risk conditions are used to generate this recommendation."}
          </p>

          <div className="mt-4 flex items-center gap-2 rounded-lg bg-slate-50 p-3">
            <ArrowRight className="h-4 w-4 text-slate-600" />

            <p className="text-sm font-semibold text-slate-800">
              Recommended Action:
            </p>

            <p className="text-sm text-slate-600">
              {highestPriority.action}
            </p>
          </div>

        </div>
      )}

      {/* Action List */}
      <div className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm">

        <h2 className="text-lg font-bold text-slate-900">
          Recommended Actions
        </h2>

        <p className="mt-1 text-sm text-slate-500">
          Backend-generated flood response recommendations.
        </p>

        <div className="mt-5 space-y-4">

          {actions.map((item, index) => {
            const Icon = item.icon;

            return (
              <div
                key={`${item.location}-${index}`}
                className="rounded-lg border border-slate-200 p-4"
              >
                <div className="flex items-start gap-4">

                  <div className="rounded-lg bg-slate-100 p-3">
                    <Icon className="h-5 w-5 text-slate-700" />
                  </div>

                  <div className="flex-1">

                    <div className="flex flex-col gap-2 md:flex-row md:items-center md:justify-between">

                      <div>
                        <h3 className="font-bold text-slate-900">
                          {item.location}
                        </h3>

                        <span
                          className={`text-xs font-bold ${
                            item.priority === "Immediate"
                              ? "text-red-600"
                              : item.priority === "High"
                              ? "text-orange-600"
                              : "text-yellow-600"
                          }`}
                        >
                          {item.priority}
                        </span>
                      </div>

                      <div className="text-sm text-slate-500">
                        Risk: {item.risk ?? "Demo"}
                      </div>

                    </div>

                    <p className="mt-2 text-sm text-slate-600">
                      {item.reason}
                    </p>

                    <div className="mt-3 flex items-center gap-2">
                      <ArrowRight className="h-4 w-4 text-slate-500" />

                      <p className="text-sm font-semibold text-slate-800">
                        {item.action}
                      </p>
                    </div>

                  </div>

                </div>
              </div>
            );
          })}

        </div>
      </div>

      {/* Prototype Notice */}
      <div className="rounded-lg border border-slate-200 bg-slate-50 px-4 py-3 text-xs text-slate-500">
        <strong>Prototype Notice:</strong>{" "}
        Recommendations shown here are generated from simulated
        backend flood conditions using transparent rule-based
        logic. They are not real emergency instructions. Actual
        emergency actions should be issued only by authorized
        authorities.
      </div>

    </div>
  );
}
