import { useEffect, useState } from "react";
import {
  Brain,
  Bell,
  Wrench,
  Route,
  ShieldAlert,
  CheckCircle,
  Clock,
  ArrowRight,
} from "lucide-react";
import { getActionRecommendations } from "../services/api";

type ActionItem = {
  priority: string;
  location: string;
  action: string;
  risk?: string;
  time?: string;
  reason?: string;
  icon: typeof ShieldAlert;
};

const fallbackActions: ActionItem[] = [
  {
    priority: "Immediate",
    location: "Saidapet",
    risk: "91/100",
    time: "45–60 min",
    reason: "Rapid water-level rise + drainage stress",
    action: "Prioritize emergency response and official evacuation procedures",
    icon: ShieldAlert,
  },
  {
    priority: "High",
    location: "Velachery",
    risk: "78/100",
    time: "1–2 hr",
    reason: "Heavy rainfall + high drainage utilization",
    action: "Issue warning and inspect vulnerable drainage points",
    icon: Bell,
  },
  {
    priority: "High",
    location: "T. Nagar",
    risk: "72/100",
    time: "2–3 hr",
    reason: "Increasing rainfall + low-lying roads",
    action: "Monitor flood-prone roads and prepare alternate routes",
    icon: Route,
  },
  {
    priority: "Monitor",
    location: "Adyar",
    risk: "48/100",
    time: "3+ hr",
    reason: "Moderate rainfall with stable water levels",
    action: "Continue monitoring rainfall and water-level trends",
    icon: Clock,
  },
];

const workflow = [
  "Risk Detected",
  "Action Generated",
  "Authority Notification",
  "Citizen Warning",
  "Traffic Management",
  "Shelter Activation",
];

function getIcon(priority: string) {
  if (priority === "Immediate") return ShieldAlert;
  if (priority === "High") return Bell;
  return Clock;
}

export default function AIActionEngine() {
  const [actions, setActions] = useState<ActionItem[]>(fallbackActions);
  const [loading, setLoading] = useState(true);
  const [backendError, setBackendError] = useState(false);

  useEffect(() => {
    async function loadActions() {
      try {
        setLoading(true);
        setBackendError(false);
        const response = await getActionRecommendations();
        if (Array.isArray(response?.recommendations)) {
          const mappedActions: ActionItem[] = response.recommendations.map(
            (item: any) => ({
              priority: item.priority,
              location: item.area,
              action: item.action,
              risk: item.priority,
              time: "Demo",
              reason: "Recommendation generated from simulated backend flood-risk conditions",
              icon: getIcon(item.priority),
            })
          );
          setActions(mappedActions);
        }
      } catch (error) {
        console.error("AI Action Engine backend error:", error);
        setBackendError(true);
        setActions(fallbackActions);
      } finally {
        setLoading(false);
      }
    }
    loadActions();
  }, []);

  const criticalCount = actions.filter((item) => item.priority === "Immediate").length;
  const highCount = actions.filter((item) => item.priority === "High").length;
  const highestPriority =
    actions.find((item) => item.priority === "Immediate")??
    actions.find((item) => item.priority === "High")??
    actions[0];

  return (
    <div className="space-y-6">
      {/* Backend Status */}
      {loading && (
        <div className="rounded-xl border border-blue-200 bg-blue-50 p-4">
          <p className="text-sm font-semibold text-blue-900">Loading action recommendations...</p>
        </div>
      )}
      {backendError &&!loading && (
        <div className="rounded-xl border border-amber-200 bg-amber-50 p-4">
          <p className="text-sm font-semibold text-amber-900">
            Backend unavailable — showing DEMO / SIMULATED DATA.
          </p>
        </div>
      )}

      {/* Header */}
      <div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
        <div>
          <div className="flex items-center gap-2">
            <Brain className="h-7 w-7 text-blue-600" />
            <h1 className="text-2xl font-bold text-slate-900">AI Action Engine</h1>
          </div>
          <p className="mt-1 text-sm text-slate-500">
            Convert predicted flood risk into prioritized response actions.
          </p>
        </div>
        <div className="rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-xs font-semibold text-amber-700">
          DEMO / SIMULATED DATA
        </div>
      </div>

      {/* Summary Cards */}
      <div className="grid gap-4 md:grid-cols-3">
        <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
          <p className="text-sm text-slate-500">Total Recommendations</p>
          <p className="mt-2 text-3xl font-bold text-slate-900">{actions.length}</p>
          <p className="mt-2 text-xs text-slate-500">Generated by backend</p>
        </div>
        <div className="rounded-xl border border-red-200 bg-red-50 p-5 shadow-sm">
          <p className="text-sm text-red-600">Immediate Actions</p>
          <p className="mt-2 text-3xl font-bold text-red-700">{criticalCount}</p>
          <p className="mt-2 text-xs text-red-600">Requires proactive response</p>
        </div>
        <div className="rounded-xl border border-orange-200 bg-orange-50 p-5 shadow-sm">
          <p className="text-sm text-orange-600">High Priority</p>
          <p className="mt-2 text-3xl font-bold text-orange-700">{highCount}</p>
          <p className="mt-2 text-xs text-orange-600">Requires monitoring and response</p>
        </div>
      </div>

      {/* Highest Priority */}
      {highestPriority && (
        <div className="rounded-xl border border-red-200 bg-white p-6 shadow-sm">
          <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
            <div className="flex items-center gap-2">
              <ShieldAlert className="h-6 w-6 text-red-600" />
              <h2 className="text-lg font-bold text-red-900">AI Decision Card</h2>
            </div>
            <span className="w-fit rounded-full bg-red-100 px-3 py-1 text-xs font-bold text-red-700">
              {highestPriority.priority.toUpperCase()}
            </span>
          </div>
          <div className="mt-4 grid grid-cols-1 gap-5 lg:grid-cols-3">
            <div>
              <p className="text-xs uppercase text-slate-500">Location</p>
              <p className="mt-2 text-xl font-bold text-slate-900">{highestPriority.location}</p>
            </div>
            <div>
              <p className="text-xs uppercase text-slate-500">Priority</p>
              <p className="mt-1 text-xl font-bold text-red-600">{highestPriority.risk?? "Backend"}</p>
            </div>
            <div>
              <p className="text-xs uppercase text-slate-500">Expected Time</p>
              <p className="mt-1 text-xl font-bold text-orange-600">{highestPriority.time?? "Demo"}</p>
            </div>
          </div>
          <p className="mt-4 text-sm text-slate-600">
            {highestPriority.reason?? "Backend simulated flood-risk conditions are used to generate this recommendation."}
          </p>
          <div className="mt-4 flex items-center gap-2 rounded-lg bg-slate-50 p-3">
            <ArrowRight className="h-4 w-4 text-slate-600" />
            <p className="text-sm font-semibold text-slate-800">Recommended Action: {highestPriority.action}</p>
          </div>
          <div className="mt-5 grid grid-cols-1 gap-3 md:grid-cols-2">
            {[
              ["Inspect Drainage", Wrench],
              ["Create Warning", Bell],
              ["View Safer Route", Route],
              ["Run Simulation", Brain],
            ].map(([label, Icon]) => {
              const ActionIcon = Icon as typeof Wrench;
              return (
                <button key={label as string} className="flex items-center justify-between rounded-lg border border-slate-200 bg-white p-4 text-left transition hover:border-blue-300 hover:bg-blue-50">
                  <div className="flex items-center gap-3">
                    <div className="rounded-lg bg-blue-50 p-2">
                      <ActionIcon className="h-5 w-5 text-blue-600" />
                    </div>
                    <span className="text-sm font-semibold text-slate-800">{label as string}</span>
                  </div>
                  <ArrowRight className="h-4 w-4 text-slate-400" />
                </button>
              );
            })}
          </div>
        </div>
      )}

      {/* Action List */}
      <div className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
        <h2 className="text-lg font-bold text-slate-900">Recommended Actions</h2>
        <p className="mt-1 text-sm text-slate-500">Backend-generated flood response recommendations.</p>
        <div className="mt-5 space-y-4">
          {actions.map((item, index) => {
            const Icon = item.icon;
            return (
              <div key={`${item.location}-${index}`} className="rounded-lg border border-slate-200 p-4">
                <div className="flex flex-col gap-4 lg:flex-row lg:items-center">
                  <div className="flex items-center gap-3 lg:w-48">
                    <div className="rounded-lg bg-slate-100 p-3">
                      <Icon className="h-5 w-5 text-slate-700" />
                    </div>
                    <div>
                      <h3 className="font-bold text-slate-900">{item.location}</h3>
                      <span className={`text-xs font-bold ${item.priority === "Immediate"? "text-red-600" : item.priority === "High"? "text-orange-600" : "text-yellow-600"}`}>
                        {item.priority}
                      </span>
                    </div>
                  </div>
                  <div className="flex-1">
                    <div className="text-sm text-slate-500">Priority: {item.risk ?? "Demo"}</div>
                    <p className="mt-2 text-sm text-slate-600">{item.reason}</p>
                    <div className="mt-3 flex items-center gap-2">
                      <ArrowRight className="h-4 w-4 text-slate-500" />
                      <p className="text-sm font-semibold text-slate-800">{item.action}</p>
                    </div>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Response Workflow */}
      <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
        <div className="flex items-center gap-2">
          <CheckCircle className="h-5 w-5 text-blue-600" />
          <h2 className="text-lg font-semibold text-slate-900">Response Workflow</h2>
        </div>
        <p className="mt-1 text-sm text-slate-500">Example flow from flood-risk detection to coordinated response.</p>
        <div className="mt-6 grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-6">
          {workflow.map((step, index) => (
            <div key={step} className="relative rounded-lg border border-slate-200 bg-slate-50 p-4">
              <div className="flex h-8 w-8 items-center justify-center rounded-full bg-blue-100 text-sm font-bold text-blue-700">
                {index + 1}
              </div>
              <p className="mt-3 text-sm font-semibold text-slate-800">{step}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Prototype Notice */}
      <div className="rounded-lg border border-slate-200 bg-slate-50 px-4 py-3 text-xs text-slate-500">
        <strong>Prototype Notice:</strong> Recommendations shown here are generated from simulated backend flood conditions using transparent rule-based logic. They are not real emergency instructions. Actual emergency actions should be issued only by authorized authorities.
      </div>
    </div>
  );
}

      


